/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IWSTokenManagement } from "./IWSTokenManagement";
export type { IWSTokensManagement } from "./IWSTokensManagement";
