/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWhitelistingManager,
  IWhitelistingManagerInterface,
} from "../../../../contracts/protocol/Interfaces/IWhitelistingManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_creator",
        type: "address",
      },
    ],
    name: "isValidToCreateWrappedSong",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nftContract",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nftRequirementEnabled",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newNFTContract",
        type: "address",
      },
    ],
    name: "setNFTContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "_enabled",
        type: "bool",
      },
    ],
    name: "toggleNFTRequirement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWhitelistingManager__factory {
  static readonly abi = _abi;
  static createInterface(): IWhitelistingManagerInterface {
    return new Interface(_abi) as IWhitelistingManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWhitelistingManager {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IWhitelistingManager;
  }
}
