/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IWhitelistingManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "isValidToCreateWrappedSong"
      | "nftContract"
      | "nftRequirementEnabled"
      | "setNFTContract"
      | "toggleNFTRequirement"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isValidToCreateWrappedSong",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nftContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nftRequirementEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setNFTContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleNFTRequirement",
    values: [boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "isValidToCreateWrappedSong",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nftContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nftRequirementEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNFTContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleNFTRequirement",
    data: BytesLike
  ): Result;
}

export interface IWhitelistingManager extends BaseContract {
  connect(runner?: ContractRunner | null): IWhitelistingManager;
  waitForDeployment(): Promise<this>;

  interface: IWhitelistingManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isValidToCreateWrappedSong: TypedContractMethod<
    [_creator: AddressLike],
    [boolean],
    "view"
  >;

  nftContract: TypedContractMethod<[], [string], "view">;

  nftRequirementEnabled: TypedContractMethod<[], [boolean], "view">;

  setNFTContract: TypedContractMethod<
    [_newNFTContract: AddressLike],
    [void],
    "nonpayable"
  >;

  toggleNFTRequirement: TypedContractMethod<
    [_enabled: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isValidToCreateWrappedSong"
  ): TypedContractMethod<[_creator: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nftContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nftRequirementEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setNFTContract"
  ): TypedContractMethod<[_newNFTContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "toggleNFTRequirement"
  ): TypedContractMethod<[_enabled: boolean], [void], "nonpayable">;

  filters: {};
}
