/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as alpha from "./Alpha";
export * as mock from "./Mock";
export * as songsLicense from "./SongsLicense";
export * as protocol from "./protocol";
